apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jit-hub-app-appset
  namespace: argocd
spec:
  generators:
    - clusters:
        # environment 레이블이 등록된 클러스터들(eks-a, eks-b, onprem)을 선택
        selector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - eks-a
                - eks-b
                - onprem
  template:
    metadata:
      name: '{{name}}-jit-hub-app'
    spec:
      project: jit-hub-project
      source:
        repoURL: 'https://github.com/hacksungboo/jit-hub-infra'
        #targetRevision: HEAD
        targetRevision: test/ci-cd # ci/cd 테스트용 (26.07.21 2030)
        path: charts/jit-hub-app
        helm:
          valueFiles:
            # 1단계: 공통 values 우선 적용
            - ../../gitops/values/common/jit-hub-common.yaml
            # 2단계: 클러스터 레이블에 맞게 특정 환경 values 적용 (오버라이드)
            - ../../gitops/values/{{metadata.labels.environment}}/jit-hub-values.yaml
      destination:
        server: '{{server}}'
        namespace: jit-hub
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
