auth:
  db:
    enabled: true
    image: postgres:15-alpine
    name: auth_db
    password: postgres
    user: postgres
    persistence:
      enabled: false
      size: 100Mi
      nfs:
        server: "172.16.8.203"
        path: "/nfs/shared/jithub-authdb"
  enabled: true
  image:
    repository: harbor.zeoxixx.cloud/jit-hub/auth-service # 개인 도메인 수정 필요
    tag: v1
  replicaCount: 1
  service:
    port: 8001
gateway:
  enabled: true
  image:
    repository: harbor.zeoxixx.cloud/jit-hub/jit-hub-gateway # 개인 도메인 수정 필요
    tag: v1
  replicaCount: 1
  service:
    port: 80
ingressRule:
  host: zeoxixx.cloud
  namespace: jit-hub
tourist:
  db:
    enabled: true
    image: postgres:15-alpine
    name: tourist_db
    password: postgres
    user: postgres
    persistence:
      enabled: false
      size: 100Mi
      nfs:
        server: "172.16.8.203"
        path: "/nfs/shared/jithub-touristdb"
  enabled: true
  image:
    repository: harbor.zeoxixx.cloud/jit-hub/tourist-service # 개인 도메인 수정 필요
    tag: v1
  replicaCount: 1
  service:
    port: 8004
traffic:
  db:
    enabled: true
    image: postgres:15-alpine
    name: traffic_db
    password: postgres
    user: postgres
    persistence:
      enabled: false
      size: 100Mi
      nfs:
        server: "172.16.8.203"
        path: "/nfs/shared/jithub-trafficdb"
  enabled: true
  image:
    repository: harbor.zeoxixx.cloud/jit-hub/traffic-service # 개인 도메인 수정 필요
    tag: v1
  replicaCount: 1
  service:
    port: 8003
weather:
  db:
    enabled: true
    image: postgres:15-alpine
    name: weather_db
    password: postgres
    user: postgres
    persistence:
      enabled: false
      size: 100Mi
      nfs:
        server: "172.16.8.203"
        path: "/nfs/shared/jithub-weatherdb"
  enabled: true
  image:
    repository: harbor.zeoxixx.cloud/jit-hub/weather-service # 개인 도메인 수정 필요
    tag: v1
  replicaCount: 1
  service:
    port: 8002
sllm:
  enabled: true
  image:
    repository: kimyujin1346/sllm-service
    tag: latest
  replicaCount: 1
  service:
    port: 8005
  location: "EKS"
  loki:
    mode: mock
    url: "http://onprem-monitoring-stack-loki:3100"
    query: '{cluster=~".+"}'
  ollama:
    image: ollama/ollama:0.31.2
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
