# gitops/values/eks-a/cloudflared-values.yaml
replicaCount: 1 # 평시
tunnelId: "xxxx-xxxx-xxxx-xxxx"
credentialsSecret: "cloudflared-creds"
ingress:
  - hostname: "ccmall.shop"
    service: http://gateway-service.jit-hub.svc.cluster.local:80
