apiVersion: apps/v1
kind: Deployment
metadata:
  name: sllm-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sllm-service
  template:
    metadata:
      labels:
        app: sllm-service
    spec:
      containers:
      - name: sllm-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: JITHUB_LOCATION
          value: {{ .Values.location | default "EKS" | quote }}
        - name: OLLAMA_URL
          value: "http://ollama:11434/api/generate"
        - name: LOKI_MODE
          value: {{ .Values.loki.mode | default "mock" | quote }}
        - name: LOKI_URL
          value: {{ .Values.loki.url | default "http://onprem-monitoring-stack-loki:3100" | quote }}
        - name: LOKI_QUERY
          value: {{ .Values.loki.query | default "{cluster=~\".+\"}" | quote }}
        - name: ANALYZE_API_URL
          value: "http://sllm-service:8005/analyze"
