# On-Prem 클러스터 전용 Override Values
# Umbrella Chart (Subchart) 구조에 맞게 작성

ingressRule:
  namespace: "jit-hub"
  host: "ccmall.shop"
gateway:
  replicaCount: 1
  image:
    repository: "harbor.ccmall.shop/jit-hub/jit-hub-gateway"
    tag: "79d959256720"
auth:
  replicaCount: 1
  image:
    repository: "harbor.ccmall.shop/jit-hub/auth-service"
    tag: "seed"
  db:
    enabled: true
    loadBalancerIP: "172.16.8.47"
    host: "auth-db"
    persistence:
      enabled: true
      size: 100Mi
      nfs:
        server: "172.16.8.203"
        path: "/nfs/shared/jithub-authdb"
weather:
  replicaCount: 1
  image:
    repository: "harbor.ccmall.shop/jit-hub/weather-service"
    tag: "seed"
  db:
    enabled: true
    loadBalancerIP: "172.16.8.48"
    host: "weather-db"
    persistence:
      enabled: true
      size: 100Mi
      nfs:
        server: "172.16.8.203"
        path: "/nfs/shared/jithub-weatherdb"
traffic:
  replicaCount: 1
  image:
    repository: "harbor.ccmall.shop/jit-hub/traffic-service"
    tag: "seed"
  db:
    enabled: true
    loadBalancerIP: "172.16.8.49"
    host: "traffic-db"
    persistence:
      enabled: true
      size: 100Mi
      nfs:
        server: "172.16.8.203"
        path: "/nfs/shared/jithub-trafficdb"
tourist:
  replicaCount: 1
  image:
    repository: "harbor.ccmall.shop/jit-hub/tourist-service"
    tag: "seed"
  db:
    enabled: true
    loadBalancerIP: "172.16.8.50"
    host: "tourist-db"
    persistence:
      enabled: true
      size: 100Mi
      nfs:
        server: "172.16.8.203"
        path: "/nfs/shared/jithub-touristdb"

sllm:
  enabled: true # sLLM 분석 파이프라인은 onprem에서만 활성화 (7/15 팀 결정)
  loki:
    mode: live
    url: "http://onprem-monitoring-stack-loki:3100"
