# gitops/values/onprem/monitoring-stack-values.yaml
# 온프레미스 = 중앙 허브 (모든 클러스터의 메트릭/로그 수신)

kube-prometheus-stack:
  enabled: true

  prometheus:
    service:
      type: LoadBalancer
      port: 9090
      loadBalancerIP: 172.16.8.32
    prometheusSpec:
      externalLabels:
        cluster: onprem
      # 다른 클러스터에서 remote_write로 보내는 메트릭 수신
      enableRemoteWriteReceiver: true
      retention: 30d
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 4Gi
          cpu: 2000m

  # 온프레미스에서만 Grafana 활성화 (통합 대시보드)
  grafana:
    enabled: true
    adminPassword: "admin"  # 운영 시 Secret으로 교체 필요
    service:
      type: LoadBalancer
      port: 80
      loadBalancerIP: 172.16.8.33
    sidecar:
      datasources:
        defaultDatasourceEnabled: false
    additionalDataSources:
      - name: "OnPrem"
        type: prometheus
        uid: prometheus
        url: http://onprem-monitoring-stack-ku-prometheus.monitoring:9090/
        isDefault: true
        jsonData:
          httpMethod: POST
          timeInterval: 30s
      - name: "Loki"
        type: loki
        uid: loki
        url: http://onprem-monitoring-stack-loki:3100
        access: proxy
        isDefault: false

  alertmanager:
    enabled: true

loki:
  enabled: true
  deploymentMode: SingleBinary
  chunksCache:
    enabled: false      # ★ 추가 — Pending 제거
  resultsCache:
    enabled: false      # ★ 추가  
  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0
  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      existingClaim: loki-pvc
  nfs:
    enabled: true
    server: "172.16.8.203"        # NFS 서버 IP (실제 IP로 변경 필요)
    path: "/nfs/shared/jithub-loki"   # NFS 경로
    storage: 50Gi

lokiLoadBalancer:
  enabled: true
  ip: 172.16.8.34

promtail:
  enabled: true
  config:
    clients:
      - url: http://onprem-monitoring-stack-loki:3100/loki/api/v1/push
        external_labels:
          cluster: onprem

# EKS 클러스터들의 remote_write/promtail을 받는 Ingress
ingestIngress:
  enabled: true
  domain: ccmall.shop # 도메인
  prometheusServiceName: onprem-monitoring-stack-ku-prometheus
  lokiServiceName: onprem-monitoring-stack-loki
