# gitops/values/eks-b/monitoring-stack-values.yaml
# EKS-B (DR) = 에이전트 (메트릭/로그를 온프레미스 중앙으로 전송)

kube-prometheus-stack:
  enabled: true

  prometheus:
    prometheusSpec:
      externalLabels:
        cluster: eks-b
      remoteWrite:
        - url: "https://prometheus-ingest.ccmall.shop/api/v1/write"

  grafana:
    enabled: false

  alertmanager:
    enabled: false

loki:
  enabled: false

promtail:
  enabled: true
  config:
    clients:
      - url: "https://loki-ingest.ccmall.shop/loki/api/v1/push"
        external_labels:
          cluster: eks-b
